/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export type ContractComponents = Awaited<ReturnType<typeof defineContractComponents>>;

export function defineContractComponents(world: World) {
  return {
    Game: (() => {
      return defineComponent(
        world,
        { game_id: RecsType.Number, winner: RecsType.Number, player_one: RecsType.BigInt, player_two: RecsType.BigInt },
        {
          metadata: {
            name: "Game",
            types: ["u32","enum","contractaddress","contractaddress"],
            customTypes: ["PlayerSide"],
          },
        }
      );
    })(),
    GameTurn: (() => {
      return defineComponent(
        world,
        { game_id: RecsType.Number, player_side: RecsType.Number },
        {
          metadata: {
            name: "GameTurn",
            types: ["u32","enum"],
            customTypes: ["PlayerSide"],
          },
        }
      );
    })(),
    MancalaGame: (() => {
      return defineComponent(
        world,
        { game_id: RecsType.BigInt, player_one: RecsType.BigInt, player_two: RecsType.BigInt, current_player: RecsType.BigInt, winner: RecsType.BigInt, score: RecsType.Number, is_finished: RecsType.Boolean, p1_pit1: RecsType.Number, p1_pit2: RecsType.Number, p1_pit3: RecsType.Number, p1_pit4: RecsType.Number, p1_pit5: RecsType.Number, p1_pit6: RecsType.Number, p2_pit1: RecsType.Number, p2_pit2: RecsType.Number, p2_pit3: RecsType.Number, p2_pit4: RecsType.Number, p2_pit5: RecsType.Number, p2_pit6: RecsType.Number, p1_store: RecsType.BigInt, p2_store: RecsType.BigInt },
        {
          metadata: {
            name: "MancalaGame",
            types: ["u128","contractaddress","contractaddress","contractaddress","contractaddress","u8","bool","u8","u8","u8","u8","u8","u8","u8","u8","u8","u8","u8","u8","u256","u256"],
            customTypes: [],
          },
        }
      );
    })(),
    Moves: (() => {
      return defineComponent(
        world,
        { player: RecsType.BigInt, count: RecsType.Number, last_decision: RecsType.Number },
        {
          metadata: {
            name: "Moves",
            types: ["contractaddress","u8","enum"],
            customTypes: ["Direction"],
          },
        }
      );
    })(),
    Player: (() => {
      return defineComponent(
        world,
        { game_id: RecsType.Number, address: RecsType.BigInt, pending_seeds: RecsType.Number, side: RecsType.Number },
        {
          metadata: {
            name: "Player",
            types: ["u32","contractaddress","u32","enum"],
            customTypes: ["PlayerSide"],
          },
        }
      );
    })(),
    Seed: (() => {
      return defineComponent(
        world,
        { game_id: RecsType.Number, position: { x: RecsType.Number, y: RecsType.Number }, player_side: RecsType.Number },
        {
          metadata: {
            name: "Seed",
            types: ["u32","u32","u32","enum"],
            customTypes: ["Vec2","PlayerSide"],
          },
        }
      );
    })(),
  };
}
